<!DOCTYPE html>
<html lang="en">

<head>
  <title>Terms and Conditions - Qi Coil WebApp (BETA)</title>
  <?php include 'head.php'; ?>
</head>
<style>

</style>
</head>

<body>
  <?php include 'header.php'; ?>

  <section>

    <div class="container">
      <div class="row">

        <div class="col-md-12">
          <h1 style="text-align: center;"><strong><u>Terms Of Service</u></strong></h1>
<p><span>Welcome to the QI Life Store Technology Website (<strong>“Website”</strong>, <strong>“we”</strong>, <strong>“us”</strong> or <strong>“our”</strong>) </span></p>
<p><span>By placing an order with us for Products which are sold on members.qicoil.com (<strong>“Products”</strong>), the Customer (<strong>“you” or “your”</strong>) will be deemed to have read, understood and agreed to these Terms and Conditions of Sale (<strong>“Agreement” or “Terms”</strong>) Please read this Agreement carefully and, if you are unhappy with any aspect of these, then you should contact us at support@qilifestore.com before placing an order with us.</span></p>
<p><span>We amend this Agreement from time to time. Please look at the top of this Agreement to see when this Agreement was last updated. Every time you order Products from us, the Agreement in force at the time of your order will apply to the contract between you and us. If we have to revise this Agreement and this has a material impact on your order, we will contact you to give you reasonable advance notice of the changes and let you know how to cancel your order if you are not happy with the changes.</span></p>
<ol>
<li><strong> Binding Agreement:</strong></li>
</ol>
<p><span>This shall be a binding agreement. It may not be altered, supplemented or amended by any other document, unless the new document is signed by both you and the Website. In addition, Terms of Service, Privacy Policy, Satisfaction Guarantee &amp; Refund Policy and Disclaimer may apply to your purchase.</span></p>
<ol start="2">
<li><strong> Entire Agreement:</strong></li>
</ol>
<p><span>This Agreement and any attachments, schedules, addenda and exhibits are together one agreement and forms the entire agreement between the parties related to the Services to be performed by the Website. This Agreement supersedes any prior representations or agreements, oral or written, and all other communications between the parties related to the subject matter. Any conflicting additional or different terms contained in any other agreement, invoice or statement of work, as the case may be, are expressly rejected.</span></p>
<ol start="3">
<li><strong> Purchase:</strong></li>
</ol>
<p><span>The Products available on the Website are for personal use only. You may not sell, resell or lease any of the Products or service you purchase or otherwise receive from us. We reserve the right, with or without notice, to cancel or reduce the quantity of any order that we believe, in our sole discretion, may result in the violation of the Agreement.</span></p>
<ol start="4">
<li><strong> Orders:</strong></li>
</ol>
<p><span>An order placed by you on the Website for Products is only an offer by you to purchase a product for the price displayed on the Website. We reserve the right to accept or reject your offer for any reason. Reasons may include, but are not limited to, the unavailability of a product or service or an error or change in the price displayed on the Website.</span></p>
<ol start="5">
<li><strong> Pricing:</strong></li>
</ol>
<p><span>The Website strives to communicate accurate pricing and product information, but will not be held responsible for any pricing, typographical, or other errors in such communication. The prices of the Products displayed on the Website may change from time to time. Prices listed on the website are exclusive of taxes. Prices are exclusive of goods and services tax and it is the Customer shall pay said tax where required. The Prices of the Products displayed on the Website are in American Dollars.</span></p>
<ol start="6">
<li><strong> Theft:</strong></li>
</ol>
<p><span>Theft or suspected Theft of the Products after Products have been shipped to the delivery address shall not be deemed to be the responsibility of the courier or the Website. You shall continue to be responsible to pay any remaining payments, in such case.</span></p>
<ol start="7">
<li><strong> Release from Liability:</strong></li>
</ol>
<p><span>To the extent permitted by Applicable Law, you release the Website and its Affiliates, and its and their employees, agents and representatives from any and all liability, damage or loss. If the Product is damaged, it may be replaced under the Refund Policy. Users who take iron supplements will be more sensitive to the effects of the Qi Coil. Symptoms include minor joint discomfort. We recommend using the devices slowly while your body adjusts to the energetic frequencies. Iron supplement users who use the Qi Coils report that they require lower doses of iron than what they usually take. Products offered qilifestore.com are NOT medical devices nor electrical appliances and they are not intended to be used to diagnose, treat, cure or prevent any disease. Products on qilifestore.com have not been evaluated by the FDA and no medical claims are made or implied for any products on qilifestore.com. We are committed to complete compliance with FDA regulations and as such, because these products have not been evaluated by the FDA, we make no claims as to any benefits for these products. If you decide to purchase Products, you are drawing your own opinions as to any additional benefits or use these products may provide. Our research, videos or testimonials on our site or others are not offered to suggest or imply that you will achieve similar results with use of our Products and methods. Studies, videos, testimonials and links provided are for reference purposes only and our products are not intended to be used to diagnose, treat, cure or prevent any disease. The aforementioned information has not been evaluated by U.S. Food and Drug Administration. Worldwide, there are no governmental health agencies that recognize a need to supplement natural magnetic fields. Always consult with your doctor before starting any use. Content on this site is no way to be considered professional medical advice; they are opinions. Unless otherwise stated, none of the authors are valid medical professionals. This site is for educational purposes only! We encourage you to use the information and links on this site with your doctor. Information and opinions provided on our website are based upon reputably published journals and firsthand experience. Information found and opinions expressed anywhere on our web site or in printed materials are never to be construed as medical advice. You understand that when you order the Qi Coil, Gem Laser or Mantra Coil, it is not a medical device or electrical appliance. If you purchase an amplifier separately from a 3rd party source and connect it to the device, you assume all liability and responsibility for converting it into an electrical device. You also hereby release the Website and its Affiliates, and its and their employees, agents and representatives from any and all from any liability for injury to yourself or others, or any property from operating the products by itself or together with an amplifier.
</span></p>

<ol start="8">
<li><strong> SMS/MMS Mobile Message Marketing Program Terms and Conditions</strong></li>
</ol>
<p><strong>8a. User Opt In:</strong></p>
<p><span>The Program allows Users to receive SMS/MMS mobile messages by affirmatively opting into the program/platform offered by us, such as through online or application-based enrollment forms(“Platform” or “Program”). Regardless of the opt-in method you utilized to join the Program, you agree that this Agreement applies to your participation in the Program.  By participating in the Program, you agree to receive autodialed or prerecorded marketing mobile messages at the phone number associated with your opt-in, and you understand that consent is not required to make any purchase from Us.  While you consent to receive messages sent using an auto dialer, the foregoing shall not be interpreted to suggest or imply that any or all of Our mobile messages are sent using an automatic telephone dialing system (“ATDS” or “auto dialer”).  <strong>Message and data rates may apply.</strong>  </span></p>
<p><strong>8b. User Opt Out:</strong></p>
<p><span>If you do not wish to continue participating in the Program or no longer agree to this Agreement, you agree to reply STOP, END, CANCEL, UNSUBSCRIBE, or QUIT to any mobile message from Us in order to opt out of the Program.  You may receive an additional mobile message confirming your decision to opt out. You understand and agree that the foregoing options are the only reasonable methods of opting out.  You also understand and agree that any other method of opting out, including, but not limited to, texting words other than those set forth above or verbally requesting one of our employees to remove you from our list, is not a reasonable means of opting out.</span></p>
<p><strong>8c. Duty to Notify and Indemnify:</span></u></strong><u><span>  </span></u></p>
<p><span>If at any time you intend to stop using the mobile telephone number that has been used to subscribe to the Program, including canceling your service plan or selling or transferring the phone number to another party, you agree that you will complete the User Opt Out process set forth above prior to ending your use of the mobile telephone number.  You understand and agree that your agreement to do so is a material part of these terms and conditions.  You further agree that, <strong>if you discontinue the use of your mobile telephone number without notifying Us of such change, you agree that you will be responsible for all costs (including attorneys’ fees) and liabilities incurred by Us, or any party that assists in the delivery of the mobile messages, as a result of claims brought by individual(s) who are later assigned that mobile telephone number.</strong> This duty and agreement shall survive any cancellation or termination of your agreement to participate in any of our Programs. </span></p>
<p><strong><span>YOU AGREE THAT YOU SHALL INDEMNIFY, DEFEND, AND HOLD US HARMLESS FROM ANY CLAIM OR LIABILITY RESULTING FROM YOUR FAILURE TO NOTIFY US OF A CHANGE IN THE INFORMATION YOU HAVE PROVIDED, INCLUDING ANY CLAIM OR LIABILITY UNDER THE TELEPHONE CONSUMER PROTECTION ACT, 47 U.S.C. § 227, et seq., OR SIMILAR STATE AND FEDERAL LAWS, AND ANY REGULATIONS PROMULGATED THEREUNDER RESULTING FROM US ATTEMPTING TO CONTACT YOU AT THE MOBILE TELEPHONE NUMBER YOU PROVIDED.</span></strong></p>
<p><strong>8d. Program Description:</strong></p>
<p><span>Without limiting the scope of the Program, users that opt into the Program can expect to receive messages concerning the marketing and sale of any products inside QiLifeStore.com, Resonantwand.com and StaffofLegends.com and anything related to the company. You would also be receiving messages regarding general information and  how to use the products that the company offers.</span></p>
<p><strong>8e. Cost and Frequency:</strong></p>
<p><span>Message and data rates may apply. The Program involves recurring mobile messages, and additional mobile messages may be sent periodically based on your interaction with Us.</span></p>
<p><strong>8f. Support Instructions:</strong></p>
<p><span>For support regarding the Program, text “HELP” to the number you received messages from or email us at <a href="mailto:support@qilifestore.com">support@qilifestore.com</a>. Please note that the use of this email address is not an acceptable method of opting out of the program. Opt outs must be submitted in accordance with the procedures set forth above.</span></p>
<p><strong>8g. MMS Disclosure:</strong></p>
<p><span>The Program will send SMS TMs (terminating messages) if your mobile device does not support MMS messaging.</span></p>
<p><strong>8h. Our Disclaimer of Warranty:</strong></p>
<p><span>The Program is offered on an "as-is" basis and may not be available in all areas at all times and may not continue to work in the event of product, software, coverage or other changes made by your wireless carrier. We will not be liable for any delays or failures in the receipt of any mobile messages connected with this Program. Delivery of mobile messages is subject to effective transmission from your wireless service provider/network operator and is outside of Our control. T-Mobile is not liable for delayed or undelivered mobile messages.</span></p>
<p><strong>8i. Participant Requirements:</span></u></strong> <span> </span></p>
<p><span>You must have a wireless device of your own, capable of two-way messaging, be using a participating wireless carrier, and be a wireless service subscriber with text messaging service. Not all cellular phone providers carry the necessary service to participate. Check your phone capabilities for specific text messaging instructions.</span></p>
<p><strong>8j. Age Restriction:</strong></p>
<p><span>You may not use of engage with the Platform if you are under thirteen (13) years of age.  If you use or engage with the Platform and are between the ages of thirteen (13) and eighteen (18) years of age, you must have your parent’s or legal guardian’s permission to do so.  By using or engaging with the Platform, you acknowledge and agree that you are not under the age of thirteen (13) years, are between the ages of thirteen (13) and eighteen (18) and have your parent’s or legal guardian’s permission to use or engage with the Platform, or are of adult age in your jurisdiction.  By using or engaging with the Platform, you also acknowledge and agree that you are permitted by your jurisdiction’s Applicable Law to use and/or engage with the Platform. </span></p>
<p><strong>8k. Prohibited Content:</span></u></strong><span>  You acknowledge and agree to not send any prohibited content over the Platform.  Prohibited content includes:</span></p>
<ol>
<li><span>Any fraudulent, libelous, defamatory, scandalous, threatening, harassing, or stalking activity;</span></li>
<li><span>Objectionable content, including profanity, obscenity, lasciviousness, violence, bigotry, hatred, and discrimination on the basis of race, sex, religion, nationality, disability, sexual orientation, or age;</span></li>
<li><span>Pirated computer programs, viruses, worms, Trojan horses, or other harmful code;</span></li>
<li><span>Any product, service, or promotion that is unlawful where such product, service, or promotion thereof is received; </span></li>
<li><span>Any content that implicates and/or references personal health information that is protected by the Health Insurance Portability and Accountability Act (“HIPAA”) or the Health Information Technology for Economic and Clinical Health Act (“HITEC” Act); and</span></li>
<li><span>Any other content that is prohibited by Applicable Law in the jurisdiction from which the message is sent.</span></li>
</ol>
<ol start="9">
<li><strong> Dispute Resolution:</strong></li>
</ol>
<p><span>In the event that there is a dispute, claim, or controversy between you and us, or between you and Stodge, LLC d/b/a Postscript or any other third-party service provider acting on Our behalf to transmit the mobile messages within the scope of the Program, arising out of or relating to federal or state statutory claims, common law claims, this Agreement, or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, such dispute, claim, or controversy will be, to the fullest extent permitted by law, determined by arbitration in British Columbia, Canada before one arbitrator.</span></p>
<p><span>The parties agree to submit the dispute to binding arbitration in accordance with the Commercial Arbitration Rules of the American Arbitration Association (“AAA”) then in effect. Except as otherwise provided herein, the arbitrator shall apply the substantive laws of British Columbia, Canada in which Qi Life Store’s principle place of business is located, without regard to its conflict of laws rules. Within ten (10) calendar days after the arbitration demand is served upon a party, the parties must jointly select an arbitrator with at least five years’ experience in that capacity and who has knowledge of and experience with the subject matter of the dispute.  If the parties do not agree on an arbitrator within ten (10) calendar days, a party may petition the AAA to appoint an arbitrator, who must satisfy the same experience requirement. In the event of a dispute, the arbitrator shall decide the enforceability and interpretation of this arbitration agreement in accordance with the Federal Arbitration Act (“FAA”).  The parties also agree that the AAA’s rules governing Emergency Measures of Protection shall apply in lieu of seeking emergency injunctive relief from a court. The decision of the arbitrator shall be final and binding, and no party shall have rights of appeal except for those provided in section 10 of the FAA. Each party shall bear its share of the fees paid for the arbitrator and the administration of the arbitration; however, the arbitrator shall have the power to order one party to pay all or any portion of such fees as part of a well-reasoned decision.  The parties agree that the arbitrator shall have the authority to award attorneys’ fees only to the extent expressly authorized by statute or contract.  The arbitrator shall have no authority to award punitive damages and each party hereby waives any right to seek or recover punitive damages with respect to any dispute resolved by arbitration. The parties agree to arbitrate solely on an individual basis, and this agreement does not permit class arbitration or any claims brought as a plaintiff or class member in any class or representative arbitration proceeding.  Except as may be required by law, neither a party nor the arbitrator may disclose the existence, content, or results of any arbitration without the prior written consent of both parties, unless to protect or pursue a legal right.  If any term or provision of this Section is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other term or provision of this Section or invalidate or render unenforceable such term or provision in any other jurisdiction.  If for any reason a dispute proceeds in court rather than in arbitration, the parties hereby waive any right to a jury trial.  This arbitration provision shall survive any cancellation or termination of your agreement to participate in any of our Programs.</span></p>
<ol start="10">
<li><strong> Miscellaneous:</strong></li>
</ol>
<p><span>You warrant and represent to Us that you have all necessary rights, power, and authority to agree to these Terms and perform your obligations hereunder, and nothing contained in this Agreement or in the performance of such obligations will place you in breach of any other contract or obligation. The failure of either party to exercise in any respect any right provided for herein will not be deemed a waiver of any further rights hereunder. If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable. Any new features, changes, updates or improvements of the Program shall be subject to this Agreement unless explicitly stated otherwise in writing. We reserve the right to change this Agreement from time to time. Any updates to this Agreement shall be communicated to you. You acknowledge your responsibility to review this Agreement from time to time and to be aware of any such changes. By continuing to participate in the Program after any such changes, you accept this Agreement, as modified.</span></p>
<ol start="11">
<li><strong> Disclaimers:</strong></li>
</ol>
<p><strong>11a. Intended Use Disclaimer:</span></u></strong><span> All products offered or advertised on this page are intended to offer customers benefits related to self-improvement, self-relaxation, personal enjoyment, entertainment and self-discovery, but are not intended to treat, diagnose, remedy or prevent any medical, physical or health conditions. All health benefits described herein are not to be relied on, and are based only on anecdotal reports. The customer or reader is responsible and liable for their own independent due diligence and research, and hereby agrees, when accessing the site or purchasing any products, that the website owner and operator is not responsible or liable for any health-related information displayed herein, and nor does the website owner vouch for its accuracy.</span></p>
<p><strong>11b. Natural Health Product Disclaimer:</span></u></strong><span> None of the products displayed on these pages are natural health products, and nor are such products regulated by health Canada, the FDA or any regulatory body. These products are consumable items with no particular ill effects on health, and may be consumed for their taste, texture, enjoyment, any mild nutritional benefits found in regular food consumption, or for other personal interest purposes, at the sole discretion of the buyer. However, these items are not health related supplements or products intended to impact, modify, treat, improve or remedy your personal health.</span></p>
<p><strong>11c. Medical Information Disclaimer:</span></u></strong><span> all health, biological or other scientific information is not to be construed as medical or health related advice. Any information must be independently verified by the reader, and the website owner is not responsible for any reliance on such information. For any health or medical related matters, the website owner urges the reader or purchaser of any goods or services on the website to consult a medical doctor for any medical or health related advice.</span></p>
<p><strong>11d. Medical Device Disclaimer:</span></u></strong><span> None of the Products Advertised on this page are intended to remedy, treat, cure, alter, diagnose, or have any noticeable or identifiable impact on or use for treating any disease or other health related condition, related to the human body, mind or public health. For any health-related concerns, the website owner urges all customers to consult with a licensed and qualified medical doctor/physician.</span></p>
<p><strong>11e. Review Disclaimer:</span></u></strong><span> The website owner is not liable or responsible for the views expressed on this page by any individuals or other third parties, which are only to be construed as the view and opinion of such individuals and third parties entirely on their own. The website owner does not endorse any such views, or the information contained in such views, and the reader or purchaser may rely on such information at their sole absolute risk.</span></p>
<p><strong>11f. Nasa Disclaimer:</span></u></strong><span> We do not intend to communicate or suggest that NASA or any other regulatory, government, or non-government body has reviewed, studied, verified or approved our products or services. Customers or visitors to our site are welcomed to verify any studies or research we describe individually, and we are not responsible for any reliance on such information.</span></p>
<p><strong>11g. Video Disclaimer:</span></u></strong><span> Please note that all the information and views provided in the video is not to be construed as advice, and such information constitutes only the opinion of the presenter or individual expressing or communicating the information. QiLifeStore.com does not endorse, vouch for or encourage any of the opinions or views of those presenting information in this video, and such views belong only to those making them. Furthermore, we do not endorse or assert the reliability, accuracy, fitness for any purpose or truth of any information, products, services or statements shown in our video, and we expect that you, the viewer, will make a researched, personally informed and independent evaluation as to the truthfulness of any information presented in this video. Do also note that any device described in this video is not a medical device under any circumstances unless explicitly stated. Therefore, any such devices shown in our video are not displayed to cure, treat or remedy any health condition or illness. For any matters related to your health, do ensure that you consult your doctor for proper diagnoses and treatment. Any consumable products displayed in this video are also not regulated or approved by any regulatory agency, and therefore you should fully research the nature and contents of such products, as well as their regulated status in the region you reside, before taking any decision to obtain, use or purchase such products.</span></p>
        </div>

      </div>
    </div>

  </section>



  <?php include 'footer.php'?>

</body>

</html>
